name: Firebase App Distribution

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  app-distribution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 17
          cache: gradle

      - name: Create google-services.json
        run: cat /home/runner/work/AniLib/AniLib/app/google-services.json | base64

      - name: Put data into google-services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/AniLib/AniLib/app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build release
        run: ./gradlew assembleRelease

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.ANILIB_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.ANILIB_FIREBASE_APP_DISTRIBUTION }}
          groups: ${{ secrets.APP_DISTRIBUTION_GROUPS }}
          file: app/build/outputs/apk/release/app-release-unsigned.apk
